add templating, fill out README
JBKLabs/example-react-project pull request #4
Opened 2019-09-23 21:49 UTC by mauleb

## Changes

* added `<% projectName %>` to various places through the project
* define a better default `README` file

## Steps to Test
* [ ] read over the `README` changes
* [ ] verify `@jbknowledge/create-react-app` replaced all of the `<% projectName %>` tokens as intended

2019-09-24 15:54 UTC, shvagen commented
@mauleb Also add template string replacement for the `name` properties in `manifest.json`.

2019-09-24 15:55 UTC, joshytaco requested changes
Finished review.

2019-09-24 15:55 UTC, joshytaco commented on README.md
> +And you run `npm run configure` while having the environment variable `ENV_SOME_ARG` set to `production value`. Your `env.js` file will be updated to:
@mauleb I think it would be a good idea to have an example of the command.

2019-09-25 20:19 UTC, mauleb commented on README.md
> +And you run `npm run configure` while having the environment variable `ENV_SOME_ARG` set to `production value`. Your `env.js` file will be updated to:
that essentially is an example.

2019-09-25 20:33 UTC, joshytaco approved these changes

2019-09-25 20:33 UTC, merged